using ServiceStandards.Application.Abstractions;
using ServiceStandards.Domain.Inventory;
using ServiceStandards.Domain.Signups;
using ServiceStandards.Domain.Tasks;

namespace ServiceStandards.Application.Tests.Fakes;

/// <summary>
/// A task store that records what it received.
/// </summary>
/// <remarks>
/// Written by hand rather than generated by a mocking library. A fake that
/// behaves like the real thing reads as code a maintainer already understands,
/// and it costs nothing in licensing or in a dependency that must keep pace
/// with the runtime.
/// </remarks>
internal sealed class FakeTaskStore : ITaskStore
{
    private const long FirstId = 1;
    private const string UpdatedTitle = "Stored task";

    private readonly List<TaskItem> _items = [];
    private long _nextId = FirstId;

    public IReadOnlyList<TaskItem> Stored => _items;

    public TaskTitle? CreatedTitle { get; private set; }

    public TaskId? CompletedId { get; private set; }

    public bool? CompletedValue { get; private set; }

    public TaskId? DeletedId { get; private set; }

    public bool ClearWasCalled { get; private set; }

    public long ClearResult { get; set; }

    public void Seed(params TaskItem[] items) => _items.AddRange(items);

    public Task<IReadOnlyList<TaskItem>> ListAsync(CancellationToken cancellationToken) =>
        Task.FromResult<IReadOnlyList<TaskItem>>(_items);

    public Task<TaskItem> CreateAsync(TaskTitle title, CancellationToken cancellationToken)
    {
        CreatedTitle = title;
        var created = new TaskItem(TaskId.From(_nextId), title, false);
        _nextId++;
        _items.Add(created);
        return Task.FromResult(created);
    }

    public Task<TaskItem> SetCompletedAsync(TaskId id, bool completed, CancellationToken cancellationToken)
    {
        CompletedId = id;
        CompletedValue = completed;
        return Task.FromResult(new TaskItem(id, TaskTitle.From(UpdatedTitle), completed));
    }

    public Task DeleteAsync(TaskId id, CancellationToken cancellationToken)
    {
        DeletedId = id;
        return Task.CompletedTask;
    }

    public Task<long> DeleteCompletedAsync(CancellationToken cancellationToken)
    {
        ClearWasCalled = true;
        return Task.FromResult(ClearResult);
    }
}

/// <summary>A signup store that answers with a fixed identifier.</summary>
internal sealed class FakeSignupStore : ISignupStore
{
    private const long AssignedId = 42;

    public Signup? Saved { get; private set; }

    public Task<SignupId> SaveAsync(Signup signup, CancellationToken cancellationToken)
    {
        Saved = signup;
        return Task.FromResult(SignupId.From(AssignedId));
    }
}

/// <summary>A stock store that answers with whatever it was seeded.</summary>
internal sealed class FakeInventoryStore : IInventoryStore
{
    private readonly List<InventoryItem> _items = [];

    public void Seed(params InventoryItem[] items) => _items.AddRange(items);

    public Task<IReadOnlyList<InventoryItem>> ItemsAsync(CancellationToken cancellationToken) =>
        Task.FromResult<IReadOnlyList<InventoryItem>>(_items);
}

/// <summary>A probe that answers, fails, or records the deadline it ran under.</summary>
internal sealed class FakeHealthProbe : IHealthProbe
{
    public Exception? Failure { get; set; }

    public bool WasCalled { get; private set; }

    public bool SawCancellableToken { get; private set; }

    public Task PingAsync(CancellationToken cancellationToken)
    {
        WasCalled = true;
        SawCancellableToken = cancellationToken.CanBeCanceled;
        return Failure is null ? Task.CompletedTask : Task.FromException(Failure);
    }
}
